version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - studio
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - studio
    volumes:
      - ./frontend:/app
networks:
  studio:
    driver: bridge
